### ISSUE TITLE
Various comments

### ISSUE THREAD

**Issue by oliverpool** [chmike/EChan#1]
Hi, let's continue our interesting discussion (https://github.com/npat-efault/musings/issues/1) here!

My latest idea of the code was the following:
```go
type Queue interface {
	Len() int
	Push(interface{})
	Pop() interface{}
}

// queueBuffered creates a buffer between the in and out channels
func queueBuffered(in <-chan interface{}, q Queue, out chan<- interface{}) {
	var head interface{}
	headOk := false

	defer func() {
		// Empty the queue before closing out
		if headOk {
			out <- head
		}
		for q.Len() > 0 {
			out <- q.Pop()
		}
		close(out)
	}()

	for {
		if !headOk {
			if q.Len() > 0 {
				head = q.Pop()
				headOk = true
			} else {
				head, headOk = <-in
				if !headOk {
					// in channel closed
					return
				}
			}
		}
		// we have a valid head
		select {
		case new, newOk := <-in:
			if !newOk {
				// in channel closed
				return
			}
			q.Push(new)
		case out <- head:
			headOk = false

		}
	}
}
```
This closes the `out` channel, when `in` is closed and `q` is empty.
It is synchronous, so one has to run `go queueBuffered(in, q, out)` (I let the caller create the channels, to let him choice regarding buffering).

--- 
I think that instead of putting a maximum size on the queue, you should use a buffered channel of this maximum size.
* Pros:
  * much faster
  * static type checked
* Cons:
  * takes the given memory size beforehand

However my code example can be simply adapted for this case, by altering the first `case` (with an additional `max` argument):
```go
case new, newOk := <-in:
	if !newOk {
		// in channel closed
		return
	}
	// queue is full: block until head is out
	if q.Len() >= max {
		out <- head
		headOk = false
	}
	q.Push(new)
```

---

By picking parts of this code, you can prevent some of the drawbacks that you mentioned:
* no need to `Close` this (it's only a function, which terminates when `in` is closed and closes `out` in turn)
* no additional channel
* no `goto`

**Comment by chmike** [comment]
Hello,

I invited you as collaborator and plan to give you full access to the repository so you can freely make your changes. 

May I suggest to make your changes in a branch and to add benchmarking code ?  The most relevant benchmarking is empty queue or low occupancy queue. We'll make the switch when superiority of your code is confirmed.

I implemented the circular buffer because I was concerned about performance. But your code would be very light and readable.

**Comment by oliverpool** [comment]
Thanks,

I've done some work on the [oliverpool](https://github.com/chmike/EChan/tree/oliverpool) branch.
It is all based on a simple interface:
```go
type Interface func(in <-chan interface{}, out chan<- interface{})
```
Take a look at the *_test.go files for examples on how to use it.
There are 4 implementations:
- immediate forwarding (read from `in` to write to `out`)
- forwarding thru buffered channel (read from `in` to write to `buf` and read from `buf` to write to `out`)
- using a "infinite" slice
- using a "ringged" slice

I've done a `Queue` interface, so that one can easily switch the backend (while keeping the same logic regarding the channel handling).
You may implement your current queue to satisfy the interface (in a subfolder of `queue`) and test it easily as well!

Some work must be done on the benchmarks, to have relevant examples (the `BenchmarkSimple` assumes very high input and output - using buffered channels)
